# DROP TABLES

songplay_table_drop = "DROP TABLE IF EXISTS FactSongPlay;"
user_table_drop = "DROP TABLE IF EXISTS DimUser;"
song_table_drop = "DROP TABLE IF EXISTS DimSong;"
artist_table_drop = "DROP TABLE IF EXISTS DimArtist;"
time_table_drop = "DROP TABLE IF EXISTS DimTime;"

# CREATE TABLES

songplay_table_create = ("""CREATE TABLE IF NOT EXISTS FactSongPlay(
                                songplay_id INT PRIMARY KEY 
                                GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
                                start_time timestamp references DimTime(start_time), 
                                user_id INT references DimUser(user_id), 
                                level VARCHAR, 
                                song_id VARCHAR references DimSong(song_id), 
                                artist_id VARCHAR references DimArtist(artist_id), 
                                session_id INT, 
                                location VARCHAR, 
                                user_agent VARCHAR)
                            """)

user_table_create = ("""CREATE TABLE IF NOT EXISTS DimUser(
                            user_id INT PRIMARY KEY, 
                            first_name VARCHAR NOT NULL, 
                            last_name VARCHAR NOT NULL, 
                            gender VARCHAR, 
                            level VARCHAR NOT NULL)
                        """)

song_table_create = ("""CREATE TABLE IF NOT EXISTS DimSong(
                            song_id VARCHAR PRIMARY KEY, 
                            title text NOT NULL, 
                            artist_id VARCHAR, 
                            year INT, 
                            duration NUMERIC)
                        """)

artist_table_create = ("""CREATE TABLE IF NOT EXISTS DimArtist(
                                artist_id VARCHAR PRIMARY KEY, 
                                name VARCHAR NOT NULL, 
                                location VARCHAR, 
                                latitude NUMERIC, 
                                longitude NUMERIC)
                            """)

time_table_create = ("""CREATE TABLE IF NOT EXISTS DimTime(
                            start_time timestamp PRIMARY KEY, 
                            hour INT, 
                            day INT, 
                            week INT,
                            month INT, 
                            year INT, 
                            weekday INT)
                        """)

# INSERT RECORDS

songplay_table_insert = ("""INSERT INTO FactSongPlay 
                            (start_time, user_id, level, song_id, artist_id, session_id, location, user_agent)
                            VALUES(%s, %s, %s, %s, %s, %s, %s, %s)
                        """)

user_table_insert = ("""INSERT INTO DimUser (user_id, first_name, last_name, gender, level)
                        VALUES(%s, %s, %s, %s, %s)
                        ON CONFLICT (user_id) 
                        DO UPDATE SET level = EXCLUDED.level
                        """)

song_table_insert = ("""INSERT INTO DimSong (song_id, title, artist_id, year, duration)
                        VALUES(%s, %s, %s, %s, %s)
                        ON CONFLICT (song_id) 
                        DO NOTHING
                        """)

artist_table_insert = ("""INSERT INTO DimArtist (artist_id, name, location, latitude, longitude)
                        VALUES(%s, %s, %s, %s, %s)
                        ON CONFLICT (artist_id) 
                        DO NOTHING
                        """)


time_table_insert = ("""INSERT INTO DimTime (start_time, hour, day, week, month, year, weekday)
                        VALUES(%s, %s, %s, %s, %s, %s, %s)
                        ON CONFLICT (start_time) 
                        DO NOTHING
                        """)

# FIND SONGS

song_select = ("""SELECT song_id, DimSong.artist_id 
                  FROM DimSong
                  JOIN DimArtist
                  ON DimSong.artist_id = DimArtist.artist_id
                  WHERE title = %s
                  AND name = %s
                  AND duration = %s
""")

# QUERY LISTS

create_table_queries = [user_table_create, song_table_create, artist_table_create, time_table_create, songplay_table_create]
drop_table_queries = [songplay_table_drop, user_table_drop, song_table_drop, artist_table_drop, time_table_drop]